[phases.setup]
nixPkgs = ["python3", "pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python main_simple.py"

[variables]
PYTHON_VERSION = "3.11"
